apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::155899448731:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1X4TAVD8EY2YI
      username: system:node:{{EC2PrivateDNSName}}
    - groups:  
      - system:masters
      rolearn: arn:aws:iam::155899448731:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-05-11T14:27:44Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
    manager: vpcLambda
    operation: Update
    time: "2023-05-11T14:27:44Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1527"
  uid: f5d9686a-38b9-4efa-a310-63d823e682f2
